layers:
 - name: BoisePoCv2
   title: Boise Proof of Concept version 2
   sources: [mbtiles_cache_v2]

caches:
  mbtiles_cache_v2:
    sources: []
    grids: [GLOBAL_MERCATOR]
    cache:
      type: mbtiles
      filename: C:/BoisePoC/mbtiles/BoisePoC_v2.mbtiles
      
services:
  wms:
    srs: ['EPSG:4326', 'EPSG:900913', 'EPSG:3857']
    versions: ['1.1.1']